### ISSUE TITLE
Epic: Registration, authentication and navigation

### ISSUE THREAD

**Issue by MartinaB91** [MartinaB91/project5-task-app-front#11]
## Description:
_This epic is about user registration, authentication and to make it possibly to navigate the page_

## User stories: 
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/7
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/8

## Tasks:
- [x]  https://github.com/MartinaB91/project5-task-app-front/issues/10
- [x]  https://github.com/MartinaB91/project5-task-app-front/issues/9

## Tests:
- [ ] https://github.com/MartinaB91/project5-task-app-front/issues/68
- [ ] https://github.com/MartinaB91/project5-task-app-front/issues/69
- [ ] https://github.com/MartinaB91/project5-task-app-front/issues/70
