### ISSUE TITLE
Epic: Search, filter, and sort tasks

### ISSUE THREAD

**Issue by MartinaB91** [MartinaB91/project5-task-app-front#15]
## Description:
_This epic is about building functionality for searching, filtering and sort tasks._

## User stories:
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/12
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/13
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/14

## Tests:
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/90
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/91
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/92
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/93
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/94
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/95
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/96
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/97
