### ISSUE TITLE
Epic: Create current family member scoreboard

### ISSUE THREAD

**Issue by MartinaB91** [MartinaB91/project5-task-app-front#16]
## Description:
_This epic is about creating the family member score board section  (results for one family member)_

## User stories: 
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/17
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/21
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/22
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/23

## Known bugs:
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/61

## Tests:
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/86
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/88
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/89
