### ISSUE TITLE
Epic: Create family scoreboard

### ISSUE THREAD

**Issue by MartinaB91** [MartinaB91/project5-task-app-front#24]
## Description:
_This epic is about creating the family score board (results for all family members)_

## User stories:
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/25
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/26
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/27
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/62

## Known bugs:
- [ ] https://github.com/MartinaB91/project5-task-app-front/issues/55
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/61

## Tests:
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/82
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/83
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/84
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/85
