### ISSUE TITLE
Epic: Task details

### ISSUE THREAD

**Issue by MartinaB91** [MartinaB91/project5-task-app-front#28]
## Description:
_This epic is about task details that are displayed on the task card (for example category, assignment and star points)._

## User stories:
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/29
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/30
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/31
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/32

## Known bugs:
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/60

## Tests:
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/77
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/78
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/79
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/80
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/81
