### ISSUE TITLE
Epic: Ability to CRUD tasks

### ISSUE THREAD

**Issue by MartinaB91** [MartinaB91/project5-task-app-front#33]
## Description:
_This epic is about create, read, update and delete tasks from the task board_

## User stories:
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/34
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/35
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/36

## Known bugs:
- [ ]  https://github.com/MartinaB91/project5-task-app-front/issues/56
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/61
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/63
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/64

## Tests:
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/73
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/74
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/75
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/76
