### ISSUE TITLE
Epic: Ability to CRUD family members 

### ISSUE THREAD

**Issue by MartinaB91** [MartinaB91/project5-task-app-front#37]
## Description:
_This epic is about create, read, update and delete family members_

## User stories:
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/38
- [ ] https://github.com/MartinaB91/project5-task-app-front/issues/39
- [ ] https://github.com/MartinaB91/project5-task-app-front/issues/40

## Known bugs:
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/58
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/65

## Tests:
- [ ] https://github.com/MartinaB91/project5-task-app-front/issues/71
- [ ] https://github.com/MartinaB91/project5-task-app-front/issues/72
