### ISSUE TITLE
Epic: System testing and final documentation

### ISSUE THREAD

**Issue by MartinaB91** [MartinaB91/project5-task-app-front#41]
## Description:
_This epic is about final documentation and testing the completed software product to evaluate the compliance of the system with the requriements._

## Known bugs:
- [ ] https://github.com/MartinaB91/project5-task-app-front/issues/101
- [ ] https://github.com/MartinaB91/project5-task-app-front/issues/99
- [ ] https://github.com/MartinaB91/project5-task-app-front/issues/56
- [ ] https://github.com/MartinaB91/project5-task-app-front/issues/55

## Tests:
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/42
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/45
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/100
