### ISSUE TITLE
Epic: Administrator handling

### ISSUE THREAD

**Issue by MartinaB91** [MartinaB91/project5-task-app-front#50]
## Description:
_This epic is about allowing admin to manage the site_

## User stories:
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/51
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/52
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/53
