### ISSUE TITLE
Epic: Project planning and design

### ISSUE THREAD

**Issue by MartinaB91** [MartinaB91/project5-task-app-front#6]
## Description:
_This epic is about planning and design of the blog project_

## Tasks:
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/1
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/2
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/3
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/4
- [x] https://github.com/MartinaB91/project5-task-app-front/issues/5
